### ISSUE TITLE
Duplicated tests

### ISSUE THREAD

**Issue by matklad** [brson/ctrs#1]
ranges-precedence.rs in 1.1.0 and 1.2.0 are different only in assertion macro being used. (`assert` vs `assert_eq`). The duplicate test in `1.2.0` should be removed, if avoiding duplicate tests is a goal of ctrs.

Here is a diff between files:

```
↪  diff 1.1.0/run-pass/ranges-precedence.rs 1.2.0/run-pass/ranges-precedence.rs                                              Tue Oct 20 12:25:42 MSK 2015
25c25
<     assert!(x == (4..9));

---
>     assert_eq!(x, (4..9));
28c28
<     assert!(x == (1..9));

---
>     assert_eq!(x, (1..9));
31c31
<     assert!(x == (4..4));

---
>     assert_eq!(x, (4..4));
35c35
<     assert!(x == (3..5));

---
>     assert_eq!(x, (3..5));
38c38
<     assert!(x == (4..));

---
>     assert_eq!(x, (4..));
40c40
<     assert!(x == (..4));

---
>     assert_eq!(x, (..4));
44c44
<     assert!(x == &a[2..4]);

---
>     assert_eq!(x, &a[2..4]);
46c46
<     assert!(x == &a[..3]);

---
>     assert_eq!(x, &a[..3]);
48c48
<     assert!(x == &a[3..]);

---
>     assert_eq!(x, &a[3..]);
57c57
<     assert!(x == (([1])..([2])));

---
>     assert_eq!(x, (([1])..([2])));
60c60
<     assert!(y == (..));

---
>     assert_eq!(y, (..));
```

**Comment by brson** [comment]
Thanks for the report.

I'm fine with removing it, but with the mechanical way this test suite is compiled it's hard to avoid these kinds of functionally-identical tests. There are scripts in-tree for deduplicating, but they only work when the source is exactly the same.

There are probably dozens of test cases that do absolutely nothing...

**Comment by matklad** [comment]
I had the false impression that tests are manually filtered :) It doesn't make sense then to remove just one duplicate
